 engines:
   duplication:
     enabled: true
     config:
       languages:
       - javascript
   eslint:
     enabled: true
   fixme:
     enabled: true
 ratings:
     paths:
     - "src/**"
 exclude_paths:
  - "node_modules/""
  - "lib/""
  - "demo/bundle.js"
  - "**.js.map"
  - "demo/benchmark.jsx"